### ISSUE TITLE
Pimp my csv2pkg

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#630]
It would save us **a lot** of time if the csv2pkg command could help us to generate a part of the catalog yaml entry. csv2pkg can guess a few elements : 
- sha256
- version: date name
- size: 145048526
- language : it depends - csv2pkg could have a look at the language column of the csv file

Some elements can't be guessed : 
- name
- description
- url
- type

So if csv2pkg could generate besides the zip file a yaml file with the same name as the zip file with something like that : 

```yaml
  entryyaml:
    name: 
    version: 2016-08-12
    url: 
    sha256sum: c04425f055a27ebebe69820601d95fba08d5febd5f142734d0642c4bf7a5089e
    size: 145048526
    language: es
    type: 
```

It would be great.
